apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-serve
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/janw4ld/GitOps-Golang_MySQL.git
    targetRevision: HEAD
    path: chart

    helm:
      values: |
        sealed:
          MYSQL_PASS: AgBW1HHJ6BLOrOIVbsLbW35VniUYYK7GXUiOLuRpmFvwKDRmc576m8otH6KT/PTJv0m1dANjAujFzaqyli++k4fZpBcg2N3a+nxzPBJs18yCWieobav5kINjrLihXbBtwYOPrag+TomZ/1tAogduCHQ8zw/RwVo/7fdOkXt9TDra2ESWERc2TrILcu8XEvnezM+XPd2sEjgxpHpCzicxZyjC85K9jTM+xGiAe72p0XOas5oJOz/Ed02O0ZTJpsamRF14tSqwv0OjCdomV1oL3jnIXKLILc+psioCBPfDcYAwapfFFZZaQwB4ljNqV0eHtfeR0CslM9J7uwWWoy2pxXfCD/ePfBA6SYQAoygZDLJMHFQHsEVVAzam6xYDa7W6iUgqg+dlc7wYrZPd83+Gf7ZBZLsERcCwWvstGkPiSbS9t9bIjQWJE8sBRP8fqvgmkr4LSu8K5aY2M/IFLNNtLdqe4zOMnaBf++KImyu89mdJRfVycuizHvOxGbdNI7xj7wQ89sEX3gvX4KfX85B1vTy6Acf6DlbcxaTtSwG7v8l5O92foDyVj1RXwgncAZXihaVbJJWkVxjff0cx/+WG0MVOz4xQXedN7yyDNNQo2swIxToQhtii5qkAFSn/TYGPwEMBIjszoCxVOi9DpnI1m9uQsHBYSTPjwnCdQMyrcBdFa7xlb5A1MXw+3Lw7QYs4PwrSY8j0r/s2cBpg977gTRUxuv6NUVEbIE8uGkJg0gZDmQ==
          MYSQL_ROOT_PASSWORD: AgA3/Ta8COq7PaghzjP2cO1ROW492TfRR6MCuvpiACyoYPDDchfvxdSr1zexATZEGxXWILlNGIcFazORs90Ba6quITIZeMIXFAHuBl7/Egwr7O3jGPjbeXjT9aevNN5eZrDviy4++e1HRS0AOCgwkvD7x+9f4YVv8Ea6ZXwHOqwAjT6HLNOZsGERPONMHwcgohk3vqNPvEuI+0MCjJEo8JwJ0+2Vo9EdR6H/9NE8QBEMdt15noT1Ksu1r34oHLtqr+yIltL9jGwvVeceEn0zOHuhSgZ0fJ4GVQuTySZLXUAAmGDTpEEFsq51/FgYId3m6oWtPvaVf9zm5h1y/vMDcSPQ0DThwHWRMGna4ZbEzHdwFb4KVSv4flCusJYI5DwboyBtxy2rM8ORRGiaNpQIjdvsVC8PXT0CIO9LWy0qv8XSolkNKc2RcpTFRgrUE/CG7FOgm5YOd+pCU4qeEx1xBhV+Sx0/mFJlC+88BTMh8MfpWiRRTvbFJludcMn4RDNGY8cuwDIpEFqp+ZMkSNZoaewMWTrvmeQpFJLY9TbE1MJJEDIcPUpLKiKiwmOegieXA8ixjL8wqAbdxYh7kQ/auONTSaysOclXnoFUbc9J5yDcThKtWnzz1O04R2jVFRhZyaplyvfoMPGC5zcTAjSY7wATiNaqC1oCygPZ9HZSLUnjE///isiPO/+FB1w1Bp+stiA5EcHYz2pqRnkiT1peGeSmK/cxzgibPI9c6c25MRcBTw==
          MYSQL_REPLICATION_PASSWORD: AgBx2+85bi1gWRvouLg4C7MEywmaa8Q4a3nX06KlWu2C3oGWBjscq0OB8W8bSx3pHAYysSTZVFRqr+vYtfjaWh3mzbEdsqHO0M9dInFqJDd67YuKgAQbjP1JzZkBF/X8HemAbpd3iYrUlSSKJU+TLyDnPWNb1GQQsFs3T6mAnIP0Mk6Bbs4f0bRwGorxl4Xf1ZfqjW72xUUA8j1Ww68AfICek6+QQEWcqjdqy804Ye7sCuWketZ7sXkGH/L1/l3HR4Y56VVPAvDkAaWl2Ji7THkHUM61rvSUAoFRfIXpPqgn3MkeCkWLgsTU+A8p5YWXKF92Af4+zgydZWajQ0FraPgIKwOryrSemrzLdUVPNrd5xr3+MRa64aK5yWqhX4BsncEwwUfElbkXyAb64B5e96fZcxuGREahplG1Zo5pmF+YrKsiFTW/n1KRjKCWntpCCYEHMRUBgPozFn+5vq0GL6DeuslZjHJUJ7LWeBYld6Tgwn/BimIZNM8NZmz8x19TbvPBCq7MCOqRg6Nfuy2aUcR/ivsT1GJMNYvmMKSoPiohlwGWPXbE8zeu0lYbbNcI1t6asSuh4xa3v5V5zhzTfKbHfHa+WXHAJCrgNcM4xysG3f85rc7wK9FOlhAgkFk8QaCgUeUYxGXnDYPf4kaV8l2nzgbkEj7iTHLuRaSVwV+BqHsDRXAslLYVHZQkQ56B8fqlwHffl+4C6wh9oSNOPU6T48f/yuwMim1ePdhrmUtxew==
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
