apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-serve
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/janw4ld/go-serve.git
    targetRevision: HEAD
    path: chart

    helm:
      valueFiles:
        - ../sealed-values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - PruneLast=true
