{{- if and (eq .Values.mysql.architecture "replication") .Values.dbLocalVolumes.create }}
{{ include "asserts.dbPrimaryPVC" . }}
{{ include "asserts.dbSecondaryPVC" . }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-primary
  labels:
    {{- include "go-serve.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  claimRef:
    name: {{ .Values.dbPrimaryPVCName }}
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: {{ .Values.dbLocalVolumes.primaryVolSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pv/{{ .Release.Name }}-primary
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-secondary
  labels:
    {{- include "go-serve.labels" . | nindent 4 }}
spec:
  storageClassName: ""
  claimRef:
    name: {{ .Values.dbSecondaryPVCName }}
    namespace: {{ .Release.Namespace }}
  capacity:
    storage: {{ .Values.dbLocalVolumes.secondaryVolSize }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /pv/{{ .Release.Name }}-secondary
{{- end }}
