apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dbPrimaryPVC }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 600Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dbSecondaryPVC }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Mi
