apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.dbSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    mysql-password: {{ .Values.sealed.MYSQL_PASS }}
    mysql-root-password: {{ .Values.sealed.MYSQL_ROOT_PASSWORD }}
    mysql-replication-password: {{ .Values.sealed.MYSQL_REPLICATION_PASSWORD }}
